# Pattern Configuration Template
# Created By: mashenquan, 2023-8-7
# File Name: template.yaml
# This template defines a set of structural standards for generating roles and action flows based on configurations.
# For more about UML 2.0 activity diagrams, see: `https://www.uml-diagrams.org/activity-diagrams.html`

# project settings
startup:
  requirement: "TeachingPlanRequirement"  # Defines project initial requirement action
  role: "Teacher"                         # Defines project role
  investment: 3.0                         # Defines the max project investment
  n_round: 1                              # Defines the max project round count

# roles settings
roles:                                    # A project can involve multiple roles.
- role_type: "fork"                       # `fork` type role corresponds to the functional positioning of the `fork` node in UML 2.0 activity diagrams.
  name: "Lily"
  profile: "{teaching_language} Teacher"
  goal: "writing a {language} teaching plan part by part"
  constraints: "writing in {language}"
  role: "You are a {teaching_language} Teacher, named Lily, your goal is ..."
  desc: ""
  output_filename: "teaching_plan_demo.md"
  requirement: ["TeachingPlanRequirement"]
  templates:                              # The template provides a convenient way to generate prompts. After each action selects its respective template, you only need to provide the corresponding variable values. Variable replacement is automatically handled by the framework.
    - "Do ..."
    - "Do ..."
  # role's action settings
  actions:                                # A role can have multiple actions.
      - name: ""
        topic: "Title"
        language: "Chinese"
        statements:                       # When replacing template variables, multiple statements will be joined into a single string using line breaks.
          - "Statement: Find and return ..."
        template_ix: 0
        rsp_begin_tag: "[..._BEGIN]"      # When asking, request the LLM to include the tag in the response. It's optional.
        rsp_end_tag: "[..._END]"          # When asking, request the LLM to include the tag in the response. It's optional.



